# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Zhe Zhang
tagline:          Systems Engineer and Researcher
url:              http://zhe-thoughts.github.io
paginate:         1
baseurl:          /
author:
  name:           Zhe Zhang
  url:            https://twitter.com/oldcap
  email:          zhe.zhang.research@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/zhe-thoughts/

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about', 'Blog':'/blog.html', 'Archive':'/archive','Feed':'/atom.xml'}
