# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Zhe Zhang
# tagline:          The Jekyll Butler
url:              http://zhe-thoughts.github.io
paginate:         1
baseurl:          /
author:
  name:           Zhe Zhang
  url:            https://twitter.com/oldcap
  email:          zhe.zhang.research@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/zhe-thoughts/
